language: android
android:
components:
# Uncomment the lines below if you want to
# use the latest revision of Android SDK Tools
# - platform-tools
# - tools

# The BuildTools version used by your project
- build-tools-26.0.2

# The SDK version used to compile your project
- android-26
- tools 
- Extra-android-support 
- extra-google-google_play_services 
- extra-android-m2repository 
- extra-google-m2repository 
- addon-google_apis-google-26 



before_install:
- chmod +x gradlew
- export JAVA8_HOME = / usr / lib / jvm / java-8-oracle 
- export JAVA_HOME = $ JAVA8_HOME 
after_success: 
- chmod + x ./upload-gh-pages. sh 
- ./upload-apk.sh 
script: 
- ./gradlew build
